In [147]:
%pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\user\anaconda3\lib\site-packages (1.0.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\user\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [148]:
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
import os
import urllib.request
import zipfile

In [149]:
class KaggleDatasetDownloader:
    def __init__(self, links, base_dir="Datasets"):
        self.links = links
        self.base_dir = os.path.abspath(base_dir)

    def download(self):
        os.makedirs(self.base_dir, exist_ok=True)

        for dataset in self.links:
            print(f"\nDownloading: {dataset}")
            path = kagglehub.dataset_download(dataset)

            dataset_name = dataset.split('/')[-1]
            save_dir = os.path.join(self.base_dir, dataset_name)
            os.makedirs(save_dir, exist_ok=True)

            print(f"Saving to: {save_dir}")

            for file in os.listdir(path):
                if file.endswith(".csv"):
                    print(f"  → {file}")
                    df = pd.read_csv(os.path.join(path, file), low_memory=False)
                    df.to_csv(os.path.join(save_dir, file), index=False)

        print("\nAll datasets saved successfully!")

    def add_dataset(self, dataset_link):
        self.links.append(dataset_link)

In [150]:
links = [
    "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
    "rounakbanik/the-movies-dataset"
]

downloader = KaggleDatasetDownloader(links)

# Run whenever you want
#downloader.download()

# Add more datasets later
# downloader.add_dataset("new/dataset-link")
# downloader.download()

In [151]:
class MovieLensDownloader:
    def __init__(self):
        self.url = "https://files.grouplens.org/datasets/movielens/ml-25m.zip"
        self.base_save_dir = os.path.abspath("Datasets")
        self.dataset_name = "movielens-25m"

        self.save_dir = os.path.join(self.base_save_dir, self.dataset_name)
        self.zip_path = os.path.join(self.save_dir, "ml-25m.zip")

    def run(self):
        # Create folder
        os.makedirs(self.save_dir, exist_ok=True)

        # Download
        print("Please wait, this might take a moment...")
        urllib.request.urlretrieve(self.url, self.zip_path)
        print("Download complete!")

        # Extract
        print("Extracting CSV files...")
        with zipfile.ZipFile(self.zip_path, 'r') as zip_ref:
            for member in zip_ref.namelist():
                filename = os.path.basename(member)

                if filename:
                    print(f"Extracting: {filename}")

                    source = zip_ref.open(member)
                    target_path = os.path.join(self.save_dir, filename)

                    with open(target_path, "wb") as target:
                        target.write(source.read())

        print("Done!")

In [152]:
ml_downloader = MovieLensDownloader()

# To download use run method
#ml_downloader.run()

In [153]:
folder_path = os.path.join("Datasets", "the-movies-dataset", "{}.csv")
files=['credits','keywords','links','links_small','movies_metadata','ratings_small','ratings']
dataframes={}
for file in files:
    dataframes[file] = pd.read_csv(folder_path.format(file),low_memory=False)

In [154]:
folder_path = os.path.join("Datasets", "movielens-25m", "{}.csv")
files=['movies','genome-tags','genome-scores']
dataframes2={}
for file in files:
    dataframes2[file] = pd.read_csv(folder_path.format(file),low_memory=False)

## IMDB 
1. IMDB dataset has response(positive/negetive) of movie with shape (50000, 2) no id 

## the-movies datset 
1. credit(45476, 3) and keywords(46419, 2) and movies_metadata(45466, 24) has a column id on which we can merge 
2. links_small (9125, 3) and links(45843, 3) has a tmdbId which is same as id of credit
3. links has shape (45843, 3) and links_small has shape (9125, 3)
4. ratings_small has a column movieid on which we can merge shape (100004, 4) 
5. rating has a column movieid shape (26024289, 4) can stack with ratings_small

##

In [155]:
credits_df=dataframes['credits']
keywords_df=dataframes['keywords']
links_df=dataframes['links']
links_small_df=dataframes['links_small']
movies_metadata_df=dataframes['movies_metadata']
ratings_df=dataframes['ratings']
ratings_small_df=dataframes['ratings_small']
movies_df=dataframes2['movies']
genome_tags_df=dataframes2['genome-tags']
genome_scores_df=dataframes2['genome-scores']

In [156]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [157]:
credits_df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cast  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]
1  [{'cast_id': 1, 'character': 'Alan Parrish', 'credit_id': '52fe44bfc3a36847f80a7c73', 'gender': 2, 'id': 2157, 'name': 'Robin Williams', 'order': 0, 'profile_path': '/sojtJyIV3lkUeThD7A2oHNm8183.jpg'}, {'cast_id': 8, 'character': 'Samuel Alan Parrish / Van Pelt', 'credit_id': '52fe44bfc3a36847f80a7c99', 'gender': 2, 'id': 8537, 'name': 'Jonathan Hyde', 'order': 1, 'profile_path': '/7il5D76vx6QVRVlpVvBPEC40MBi.jpg'}, {'cast_id': 2, 'character': 'Judy Sheperd', 'credit_id': '52fe44bfc3a36847f80a7c77', 'gender': 1, 'id': 205, 'name': 'Kirsten Dunst', 'order': 2, 'profile_path': '/wBXvh6PJd0IUVNpvatPC1kzuHtm.jpg'}, {'cast_id': 24, 'character': 'Peter Shepherd', 'credit_id': '52fe44c0c3a36847f80a7ce7', 'gender': 0, 'id': 145151, 'name': 'Bradley Pierce', 'order': 3, 'profile_path': '/j6iW0vVA23GQniAPSYI6mi4hiEW.jpg'}, {'cast_id': 10, 'character': 'Sarah Whittle', 'credit_id': '52fe44bfc3a36847f80a7c9d', 'gender': 1, 'id': 5149, 'name': 'Bonnie Hunt', 'order': 4, 'profile_path': '/7spiVQwmr8siw5QCcvvdRG3c7Lf.jpg'}, {'cast_id': 25, 'character': 'Nora Shepherd', 'credit_id': '52fe44c0c3a36847f80a7ceb', 'gender': 1, 'id': 10739, 'name': 'Bebe Neuwirth', 'order': 5, 'profile_path': '/xm58rpMRVDHS0IGttw1pTlqGwkN.jpg'}, {'cast_id': 26, 'character': 'Carl Bentley', 'credit_id': '52fe44c0c3a36847f80a7cef', 'gender': 2, 'id': 58563, 'name': 'David Alan Grier', 'order': 6, 'profile_path': '/5tkt3qRZTco4sz604aTIarQ0m8W.jpg'}, {'cast_id': 11, 'character': 'Carol Anne Parrish', 'credit_id': '52fe44bfc3a36847f80a7ca1', 'gender': 1, 'id': 1276, 'name': 'Patricia Clarkson', 'order': 7, 'profile_path': '/10ZSyaUqzUlKTd60HmeiGhlytZG.jpg'}, {'cast_id': 14, 'character': 'Alan Parrish (young)', 'credit_id': '52fe44bfc3a36847f80a7cad', 'gender': 0, 'id': 46530, 'name': 'Adam Hann-Byrd', 'order': 8, 'profile_path': '/hEoqDqtMO91hYWD5iDrDesnLDlt.jpg'}, {'cast_id': 13, 'character': 'Sarah Whittle (young)', 'credit_id': '52fe44bfc3a36847f80a7ca9', 'gender': 1, 'id': 56523, 'name': 'Laura Bell Bundy', 'order': 9, 'profile_path': '/8tAVDBRoZPjKfCbBDyh4iK9JNEp.jpg'}, {'cast_id': 31, 'character': 'Exterminator', 'credit_id': '52fe44c0c3a36847f80a7cff', 'gender': 2, 'id': 51551, 'name': 'James Handy', 'order': 10, 'profile_path': '/vm0WQmuP8jEGgFTd3VCcJe7zpUi.jpg'}, {'cast_id': 12, 'character': 'Mrs. Thomas the Realtor', 'credit_id': '52fe44bfc3a36847f80a7ca5', 'gender': 1, 'id': 56522, 'name': 'Gillian Barber', 'order': 11, 'profile_path': '/qoqPX15J5jh6Sy0A9JvvRJIuw64.jpg'}, {'cast_id': 28, 'character': 'Benjamin', 'credit_id': '52fe44c0c3a36847f80a7cf3', 'gender': 2, 'id': 1000304, 'name': 'Brandon Obray', 'order': 12, 'profile_path': None}, {'cast_id': 29, 'character': 'Caleb', 'credit_id': '52fe44c0c3a36847f80a7cf7', 'gender': 0, 'id': 188949, 'name': 'Cyrus Thiedeke', 'order': 13, 'profile_path': None}, {'cast_id': 30, 'character': 'Billy Jessup', 'credit_id': '52fe44c0c3a36847f80a7cfb', 'gender': 0, 'id': 1076551, 'name': 'Gary Joseph Thorup', 'order': 14, 'profile_path': None}, {'cast_id': 32, 'character': 'Cop', 'credit_id': '5588053fc3a36838530063f5', 'gender': 0, 'id': 1480246, 'name': 'Leonard Zola', 'order': 15, 'profile_path': None}, {'cast_id': 33, 'character': 'Bum', 'credit_id': '55935687925141645a002097', 'gender': 2, 'id': 25024, 'name': 'Lloyd Berry', 'order': 16, 'profile_path': '/s7SVCOtvcuQ9wRQPZfUdahb5x88.jpg'}, {'cast_id': 34, 'character': 'Jim Shepherd', 'credit_id': '559356d09251415df8002cb7', 'gender': 2, 'id': 27110, 'name': 'Malcolm Stewart', 'order': 17, 'profile_path': '/l2vgzkLR7GRr8ugjZCILA0OiliI.jpg'}, {'cast_id': 35, 'character': 'Martha Shepherd', 'credit_id': '55935730925141645a0020ad', 'gender': 0, 'id': 53715, 'name': 'Annabel Kershaw', 'order': 18, 'profile_path': '/1VqbvAohBwFhETZtDe76JXQcxKm.jpg'}, {'cast_id': 36, 'character': 'Gun Salesman', 'credit_id': '5593576992514167fd000610', 'gender': 2, 'id': 1379424, 'name': 'Darryl Henriques', 'order': 19, 'profile_path': '/7QMHooY9ewNQlE24WKAOdwW0evU.jpg'}, {'cast_id': 37, 'character': 'Paramedic', 'credit_id': '559357ae92514152de002f42', 'gender': 0, 'id': 1235504, 'name': 'Robyn Driscoll', 'order': 20, 'profile_path': None}, {'cast_id': 50, 'character': 'Paramedic', 'credit_id': '5657803b925141018f00a5dc', 'gender': 2, 'id': 25389, 'name': 'Peter Bryant', 'order': 21, 'profile_path': '/fkcx9Tnp25UC5HlI2eW3nGvumsZ.jpg'}, {'cast_id': 39, 'character': 'Girl', 'credit_id': '559358e292514152de002f63', 'gender': 0, 'id': 1483449, 'name': 'Sarah Gilson', 'order': 22, 'profile_path': None}, {'cast_id': 40, 'character': 'Girl', 'credit_id': '5593590d92514152db002df3', 'gender': 0, 'id': 1483450, 'name': 'Florica Vlad', 'order': 23, 'profile_path': None}, {'cast_id': 41, 'character': 'Baker', 'credit_id': '55935946c3a36869d1001b4d', 'gender': 0, 'id': 1483451, 'name': 'June Lion', 'order': 24, 'profile_path': None}, {'cast_id': 42, 'character': 'Pianist', 'credit_id': '5593597692514167fd000644', 'gender': 0, 'id': 1483452, 'name': 'Brenda Lockmuller', 'order': 25, 'profile_path': None}]

In [158]:
keywords_df.head()

,id,keywords
0,862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"
1,8844,"[{'id': 10090, 'name': 'board game'}, {'id': 10941, 'name': 'disappearance'}, {'id': 15101, 'name': ""based on children's book""}, {'id': 33467, 'name': 'new home'}, {'id': 158086, 'name': 'recluse'}, {'id': 158091, 'name': 'giant insect'}]"
2,15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392, 'name': 'best friend'}, {'id': 179431, 'name': 'duringcreditsstinger'}, {'id': 208510, 'name': 'old men'}]"
3,31357,"[{'id': 818, 'name': 'based on novel'}, {'id': 10131, 'name': 'interracial relationship'}, {'id': 14768, 'name': 'single mother'}, {'id': 15160, 'name': 'divorce'}, {'id': 33455, 'name': 'chick flick'}]"
4,11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'name': 'midlife crisis'}, {'id': 2246, 'name': 'confidence'}, {'id': 4995, 'name': 'aging'}, {'id': 5600, 'name': 'daughter'}, {'id': 10707, 'name': 'mother daughter relationship'}, {'id': 13149, 'name': 'pregnancy'}, {'id': 33358, 'name': 'contraception'}, {'id': 170521, 'name': 'gynecologist'}]"

In [159]:
links_small_df.shape

(9125, 3)

In [160]:
movies_metadata_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]",NaN,8844,tt0113497,en,Jumanji,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.",17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]",NaN,15602,tt0113228,en,Grumpier Old Men,"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.",11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for Love.,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe.",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,"[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself... and never let you forget it.,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts4iOmNnq7GNicycMJ9pSAn204.jpg', 'backdrop_path': '/7qwE57OVZmMJChBpLEbJEmzUydk.jpg'}",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,"Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home, but that's a plan that -- like George -- will have to change with the arrival of both a grandchild and a kid of his own.",8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Pictures', 'id': 9195}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,Father of the Bride Part II,False,5.7,173.0

In [161]:
combined_links = pd.concat([links_df, links_small_df], axis=0, ignore_index=True)

In [162]:
combined_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [163]:
combined_links.shape

(54968, 3)

In [164]:
combined_ratings = pd.concat([ratings_df, ratings_small_df], axis=0, ignore_index=True)

In [165]:
combined_ratings.shape

(26124293, 4)

In [166]:
combined_ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [167]:
combined_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [168]:
movies_metadata_df["id"] = pd.to_numeric(movies_metadata_df["id"], errors="coerce")

In [169]:
df = credits_df.merge(keywords_df,on="id", how="outer") \
        .merge(combined_links, left_on="id", right_on="tmdbId", how="outer") \
        .merge(movies_metadata_df,on="id", how="outer")

In [170]:
df.head(1)

,cast,crew,id,keywords,movieId,imdbId,tmdbId,adult,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,"[{'cast_id': 3, 'character': 'Taisto Olavi Kasurinen', 'credit_id': '52fe420dc3a36847f8000029', 'gender': 0, 'id': 54768, 'name': 'Turo Pajala', 'order': 0, 'profile_path': None}, {'cast_id': 4, 'character': 'Irmeli Katariina Pihlaja', 'credit_id': '52fe420dc3a36847f800002d', 'gender': 0, 'id': 54769, 'name': 'Susanna Haavisto', 'order': 1, 'profile_path': None}, {'cast_id': 5, 'character': 'Mikkonen', 'credit_id': '52fe420dc3a36847f8000031', 'gender': 2, 'id': 4826, 'name': 'Matti Pellonpää', 'order': 2, 'profile_path': '/7WuLvkuWphUAtW6QQwtF3WrwUKE.jpg'}, {'cast_id': 6, 'character': 'Riku', 'credit_id': '52fe420dc3a36847f8000035', 'gender': 0, 'id': 54770, 'name': 'Eetu Hilkamo', 'order': 3, 'profile_path': None}]","[{'credit_id': '52fe420dc3a36847f800001f', 'department': 'Writing', 'gender': 0, 'id': 16767, 'job': 'Screenplay', 'name': 'Aki Kaurismäki', 'profile_path': '/8nQcTzKUmRh6MPprd1n6iOauYPf.jpg'}, {'credit_id': '52fe420dc3a36847f8000025', 'department': 'Directing', 'gender': 0, 'id': 16767, 'job': 'Director', 'name': 'Aki Kaurismäki', 'profile_path': '/8nQcTzKUmRh6MPprd1n6iOauYPf.jpg'}, {'credit_id': '52fe420dc3a36847f800003b', 'department': 'Camera', 'gender': 2, 'id': 16769, 'job': 'Director of Photography', 'name': 'Timo Salminen', 'profile_path': None}, {'credit_id': '52fe420dc3a36847f8000041', 'department': 'Editing', 'gender': 0, 'id': 54766, 'job': 'Editor', 'name': 'Raija Talvio', 'profile_path': None}, {'credit_id': '52fe420dc3a36847f8000047', 'department': 'Art', 'gender': 2, 'id': 53836, 'job': 'Production Design', 'name': 'Risto Karhula', 'profile_path': None}, {'credit_id': '52fe420dc3a36847f800004d', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 54771, 'job': 'Costume Design', 'name': 'Tuula Hilkamo', 'profile_path': None}]",2.0,"[{'id': 240, 'name': 'underdog'}, {'id': 378, 'name': 'prison'}, {'id': 730, 'name': 'factory worker'}, {'id': 1563, 'name': 'prisoner'}, {'id': 1787, 'name': 'helsinki'}, {'id': 10183, 'name': 'independent film'}, {'id': 13072, 'name': 'falling in love'}]",4470.0,94675.0,2.0,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]",NaN,tt0094675,fi,Ariel,"Taisto Kasurinen is a Finnish coal miner whose father has just committed suicide and who is framed for a crime he did not commit. In jail, he starts to dream about leaving the country and starting a new life. He escapes from prison but things don't go as planned...",3.860491,/gZCJZOn4l0Zj5hAxsMbxoS6CL0u.jpg,"[{'name': 'Villealfa Filmproduction Oy', 'id': 2303}, {'name': 'Finnish Film Foundation', 'id': 2396}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",1988-10-21,0.0,69.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}, {'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Ariel,False,7.1,44.0

## **Basic Info About All Columns In Data**

1. `cast` has info about all actors.
2. `crew` has info about who have done all the production work.
3. Here `id`  and `tmdbId` has same id of a movie.
4. `keywords` contains tags that describe the themes or important ideas in the movie.
5. `imdbId` and `imdb_id` both are same but `imdb_id` is in right format(tt0094675) and it has some missing values so we can fill it from `imdbId`(only 1 missing values) and then we can drop `imdbId`.
6. `belongs_to_collection` column tells whether a movie is part of a series/franchise and gives the name of that collection(that's why the column has less value as all movie are not a part of series).But in some place it has some weird number that is the data is corrupted.
7. `budget` column contain info about total amount spent to produce that movie but this column also has some corrupted value.
8. `genres` has info that what type/category this movie belong to.
9. `homepage` has info about Official website URL of the movie and also in some row it contain the value which should be in `production_country` column(so we need to extract them).
10. `original_language` has info about in which language this movie is.but it contain some weired number which may be data of different column(need checking).
11. `original_title` has the title(real name of the movie in which language it is made) of the movie here in some row we have value of `spoken_language` column so the columns are mixed and also we have repeated name so need checking that are they same movie or different version of same movie.
12. `overview` has brief movie description but it is mixed up with status column as it has 'released' as value which should be in `status` column.
13. `popularity` column has scores that how popular this movie is but it is mixed up with may be `tagline` column as in some place has value like 'Beware Of Frost Bites'.
14. `production_companies` has info company name it has also value like 'False' in many rows which need to be corrected.
15. `adult` should contain two values 'False'(normal movie) and 'True' (adult movie:for 18+years) but in some places it have text(may be from overview column) like 3 text each 424 times(need checking).
16. `production_countries` give info that which country produce that movie.
17. `release_date` has info when the movie is released it is also corrupted as (12,1,22 this 3 value contain each 424 times and this colulmn also has lot of missing values).
18. `revenue` give info that how much money the movie earned (it has a lot of 0 values(43676) and nan values also)(need cleaning).
19. `runtime` contain total movie time(in min).
20. `spoken_language` contain info that what all language used in this movie.
21. `status` give current statge of movies lifecycle(so from here we have to show only those movies which are released for recomendation).
22. `tagline` is basically a short promotional sentence for marketing.
23. `title` has title(standerdized title(baiscally in english)) of the movie but it has many repeated values(so need checking are they really same movie or not).so we may be merge this column with 'original_title' column after cleaning and use that column in tf_idf.
24. `video` has info about the movie trailor availabilty in this dataset(so only two values False and True)(not usefull for TfIdf may be used for filltering).
25. `vote_average` give average rating score of that movie.
26. `vote_count` give how many users rated that movie. here we can merge this two column for filltering the movie after TfIdf.
* **`cast`,`crew`,`keywords`,`belongs_to_collection`,`genres`,`production_companies`,
`production_countries`,`spoken_language` all are in string format first need to parse them to make a list of dictionary for extract info from it.**

In [171]:
#missing value percentage in each column
(df.isnull().mean() * 100).to_frame().T

,cast,crew,id,keywords,movieId,imdbId,tmdbId,adult,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,2.217693,2.217693,2.215951,2.217693,0.001742,0.001742,1.214243,0.0,86.826243,0.0,0.0,80.275949,0.029616,0.019163,0.0,1.754294,1.484269,0.700324,0.006968,0.006968,0.153305,2.222919,2.682833,2.222919,2.369255,51.236891,2.222919,2.222919,2.222919,2.222919

In [172]:
df[df.duplicated()]

In [173]:
df[['genres','movieId','title','tmdbId']].head(6)

,genres,movieId,title,tmdbId
0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]",4470.0,Ariel,2.0
1,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]",4470.0,Ariel,2.0
2,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name': 'Comedy'}]",61724.0,Shadows in Paradise,3.0
3,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name': 'Comedy'}]",18.0,Four Rooms,5.0
4,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name': 'Comedy'}]",18.0,Four Rooms,5.0
5,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}]",479.0,Judgment Night,6.0

In [174]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [175]:
pd.set_option('display.max_columns', None)

pd.set_option('display.max_colwidth', None)
df['vote_count'].value_counts()

vote_count
1.0       3449
2.0       3294
0.0       3097
3.0       3072
4.0       2647
          ...
1959.0       1
799.0        1
651.0        1
714.0        1
357.0        1
Name: count, Length: 1820, dtype: int64

In [176]:
df.columns

Index(['cast', 'crew', 'id', 'keywords', 'movieId', 'imdbId', 'tmdbId',
       'adult', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57402 entries, 0 to 57401
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cast                   56129 non-null  object
 1   crew                   56129 non-null  object
 2   id                     56130 non-null  float64
 3   keywords               56129 non-null  object
 4   movieId                57401 non-null  float64
 5   imdbId                 57401 non-null  float64
 6   tmdbId                 56705 non-null  float64
 7   adult                  57402 non-null  object
 8   belongs_to_collection  7562 non-null   object
 9   budget                 57402 non-null  object
 10  genres                 57402 non-null  object
 11  homepage               11322 non-null  object
 12  imdb_id                57385 non-null  object
 13  original_language      57391 non-null  object
 14  original_title         57402 non-null  object
 15  overview               56395 non-null  object
 16  popularity             56550 non-null  object
 17  poster_path            57000 non-null  object
 18  production_companies   57398 non-null  object
 19  production_countries   57398 non-null  object
 20  release_date           57314 non-null  object
 21  revenue                56126 non-null  float64
 22  runtime                55862 non-null  float64
 23  spoken_languages       56126 non-null  object
 24  status                 56042 non-null  object
 25  tagline                27991 non-null  object
 26  title                  56126 non-null  object
 27  video                  56126 non-null  object
 28  vote_average           56126 non-null  float64
 29  vote_count             56126 non-null  float64
dtypes: float64(8), object(22)
memory usage: 13.1+ MB

In [178]:
print(combined_ratings['movieId'].min())
print(combined_ratings['movieId'].max())

1
176275

In [179]:
print(df['movieId'].min())
print(df['movieId'].max())

1.0
176279.0

In [180]:
combined_ratings.shape

(26124293, 4)

In [181]:
df1=df.copy()

In [182]:
print(df1['id'].duplicated().sum())
print(df1.duplicated().sum())

11968
10718

In [183]:
df1.drop_duplicates(inplace=True)

In [184]:
print(df1['id'].duplicated().sum())
print(df1.duplicated().sum())

1250
0

In [185]:
df1.columns

Index(['cast', 'crew', 'id', 'keywords', 'movieId', 'imdbId', 'tmdbId',
       'adult', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [186]:
df1[['imdbId','imdb_id']].head()

     imdbId    imdb_id
0   94675.0  tt0094675
2   92149.0  tt0092149
3  113101.0  tt0113101
5  107286.0  tt0107286
7   76759.0  tt0076759

In [187]:
print(df1['imdbId'].isnull().sum())
# print(df1['imdb_id'].isnull().sum())

1

In [188]:
df1[df1['imdbId'].isnull()][['imdbId','imdb_id']]

       imdbId    imdb_id
55208     NaN  tt3291632

In [189]:

def clean_imdb(df):

    # rows where imdbId is missing
    # but imdb_id exists
    mask = (
        df['imdbId'].isnull() &
        df['imdb_id'].notnull()
    )

    # fill imdbId using imdb_id
    df.loc[mask, 'imdbId'] = (
        df.loc[mask, 'imdb_id']
        .astype(str)
        .str.replace('tt', '', regex=False)
        .astype(float)
    )

    # convert imdbId to nullable integer
    df['imdbId'] = df['imdbId'].astype('Int64')

    return df

In [190]:
df1=clean_imdb(df1)

In [191]:
df1.drop(columns=['imdb_id'], inplace=True)

In [192]:
# used column for content-based filtering
# 1.cast
# 2.crew
# 3.keywords
# 4.belongs_to_collection
# 5.genres
# 6.Overview
# 7.tagline
# 8.

In [193]:
# The 'cast', 'crew', and 'keywords' etc columns contain string representations of lists of dictionaries. 
# We need to convert these strings back into their original list/dictionary format for easier manipulation later on.
import ast
col_name=['cast','crew','keywords','belongs_to_collection','spoken_languages','production_companies','genres','production_countries']
for item in col_name:
    df1[item] = df1[item].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])

In [194]:
def clean_cast(df):
    cleaned_cast = []

    for row in df['cast']:
        actors = []
        counter = 0

        # check if row is list
        if isinstance(row, list):
            for item in row:
                if counter != 3:
                    actors.append(
                        item['name']
                        .replace(" ", "")
                        .lower()
                    )
                    counter += 1
        cleaned_cast.append(actors)
    df['cast'] = cleaned_cast

    return df

In [195]:
df1 = clean_cast(df1)

In [196]:
df1['cast'].sample(1)

35879    [arsinéekhanjian, atomegoyan, ashotadamyan]
Name: cast, dtype: object

In [197]:
def clean_crew(df):
    cleaned_crew = []

    for row in df['crew']:
        directors = []

        if isinstance(row, list):
            for item in row:
                if item.get('job') == 'Director':
                    name = item.get('name', '')
                    directors.append(name.replace(" ", "").lower())
                    
        cleaned_crew.append(directors)
    df['crew'] = cleaned_crew

    return df

In [198]:
df1 = clean_crew(df1)

In [199]:
df1['crew'].sample(1)

43772    [billkalmenson]
Name: crew, dtype: object

In [200]:
df1['keywords'].sample(4)

3498     [{'id': 255, 'name': 'male nudity'}, {'id': 293, 'name': 'female nudity'}, {'id': 494, 'name': 'father son relationship'}, {'id': 549, 'name': 'prostitute'}, {'id': 596, 'name': 'adultery'}, {'id': 738, 'name': 'sexuality'}, {'id': 931, 'name': 'jealousy'}, {'id': 1157, 'name': 'wife husband relationship'}, {'id': 1326, 'name': 'infidelity'}, {'id': 1715, 'name': 'symbolism'}, {'id': 1849, 'name': 'homicide'}, {'id': 2983, 'name': 'passion'}, {'id': 3182, 'name': 'seduction'}, {'id': 7149, 'name': 'machismo'}, {'id': 7965, 'name': 'matador'}, {'id': 8201, 'name': 'satire'}, {'id': 10707, 'name': 'mother daughter relationship'}, {'id': 11004, 'name': 'rural setting'}, {'id': 11510, 'name': 'unfaithfulness'}, {'id': 11732, 'name': 'cigarette smoking'}, {'id': 13149, 'name': 'pregnancy'}, {'id': 15300, 'name': 'father daughter relationship'}, {'id': 33451, 'name': 'masturbation'}, {'id': 34094, 'name': 'extramarital affair'}, {'id': 41260, 'name': 'sensuality'}, {'id': 157499, 'name': 'mother son relationship'}, {'id': 167193, 'name': 'male model'}, {'id': 188991, 'name': 'drunkenness'}, {'id': 194921, 'name': 'sexual dysfunction'}, {'id': 208591, 'name': 'abortion'}, {'id': 215982, 'name': 'zaragoza spain'}, {'id': 215983, 'name': 'underwear manufacturer'}]
43102                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             []
24028                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             []
32963                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [{'id': 983, 'name': 'brazilian'}, {'id': 10637, 'name': 'food'}]
Name: keywords, dtype: object

In [201]:
def clean_keywords(df):
    cleaned = []
    
    for row in df['keywords']:
        words = []

        if isinstance(row, list):
            for item in row:
                if isinstance(item, dict) and 'name' in item: 
                    words.append(item['name'].replace(" ", "").lower())
        
        cleaned.append(words)
    
    df['keywords'] = cleaned
    return df

In [202]:
df1 = clean_keywords(df1)

In [203]:
df1['belongs_to_collection'].sample(4)

20675    []
37498    []
36860    []
27623    []
Name: belongs_to_collection, dtype: object

In [204]:
def clean_belongs_to_collection(df):

    cleaned = []

    for item in df['belongs_to_collection']:

        if isinstance(item, dict):

            name = item.get('name', '')
            name = name.replace(" ", "").lower()

            cleaned.append([name])   # LIST

        else:
            cleaned.append([])

    df['belongs_to_collection'] = cleaned

    return df

In [205]:
df1 = clean_belongs_to_collection(df1)

In [206]:
df1['belongs_to_collection'].value_counts()

belongs_to_collection
[]                                 42187
[theboweryboys]                       29
[totòcollection]                      27
[jamesbondcollection]                 26
[zatôichi:theblindswordsman]          26
                                   ...
[thekrayscollection]                   1
[aurélielaflammecollection]            1
[lassemaja:samling]                    1
[minions:3mini-moviecollection]        1
[zipiyzape-colección]                  1
Name: count, Length: 1696, dtype: int64

In [207]:
df1['keywords'].isnull().sum()

np.int64(0)

In [208]:
def clean_overview(df):

    # lowercase and strip spaces
    df['overview'] = (
        df['overview']
        .astype(str)
        .str.strip()
        .str.lower()
    )

    # replace invalid text
    df['overview'] = df['overview'].replace(
        ['no overview found.', 'no overview'],
        np.nan
    )

    # replace released with NaN
    df['overview'] = df['overview'].replace(
        'released',
        np.nan
    )

    # fill missing overview with empty string
    df['overview'] = df['overview'].fillna('')

    # split into words
    df['overview'] = df['overview'].apply(
        lambda x: x.split()
    )

    return df

In [209]:
df1= clean_overview(df1)

In [210]:
df1['overview'].sample(1)

26769    [a, physician, discovers, that, two, children, are, being, kept, virtually, imprisoned, in, their, house, by, their, father., he, investigates,, and, discovers, a, web, of, sex,, incest, and, satanic, possession.]
Name: overview, dtype: object

In [211]:
df1['genres'].sample(1)

40258    [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 10749, 'name': 'Romance'}, {'id': 10769, 'name': 'Foreign'}]
Name: genres, dtype: object

In [212]:
def clean_genres(df):
    
    cleaned_genres = []
    
    for row in df['genres']:
        
        genres = []
        
        if isinstance(row, list):
            
            for item in row:
                
                if isinstance(item, dict):
                    
                    genres.append(item.get('name', '').replace(" ", "").lower())
        
        cleaned_genres.append(genres)
    
    df['genres'] = cleaned_genres
    
    return df

In [213]:
df1=clean_genres(df1)

In [214]:
df1['genres'].sample(1)

10584    [animation]
Name: genres, dtype: object

In [215]:
df1['tagline'].sample(1)

42311    NaN
Name: tagline, dtype: object

In [216]:
df['keywords'].apply(lambda x: type(x)).value_counts()

keywords
<class 'str'>      56129
<class 'float'>     1273
Name: count, dtype: int64

In [217]:
df1.columns

Index(['cast', 'crew', 'id', 'keywords', 'movieId', 'imdbId', 'tmdbId',
       'adult', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [218]:
df1[['cast','crew','keywords','overview','belongs_to_collection','genres','tagline']].head(2)

,cast,crew,keywords,overview,belongs_to_collection,genres,tagline
0,"[turopajala, susannahaavisto, mattipellonpää]",[akikaurismäki],"[underdog, prison, factoryworker, prisoner, helsinki, independentfilm, fallinginlove]","[taisto, kasurinen, is, a, finnish, coal, miner, whose, father, has, just, committed, suicide, and, who, is, framed, for, a, crime, he, did, not, commit., in, jail,, he, starts, to, dream, about, leaving, the, country, and, starting, a, new, life., he, escapes, from, prison, but, things, don't, go, as, planned...]",[],"[drama, crime]",NaN
2,"[mattipellonpää, katioutinen, sakarikuosmanen]",[akikaurismäki],"[salesclerk, helsinki, garbage, independentfilm]","[an, episode, in, the, life, of, nikander,, a, garbage, man,, involving, the, death, of, a, co-worker,, an, affair, and, much, more.]",[],"[drama, comedy]",NaN

In [219]:
import string

# function to remove punctuation

def remove_punctuation(text):

    if isinstance(text, str):
        return text.translate(
            str.maketrans('', '', string.punctuation)
        )

    elif isinstance(text, list):
        return [
            word.translate(
                str.maketrans('', '', string.punctuation)
            )
            for word in text
        ]

    return text

In [220]:
df1['tagline'] = df1['tagline'].fillna('')
df1['tagline']=df1['tagline'].str.lower()
df1['tagline']=df1['tagline'].apply(lambda x: x.split())

In [221]:
df1['crew']

0                                                              [akikaurismäki]
2                                                              [akikaurismäki]
3        [allisonanders, alexandrerockwell, robertrodriguez, quentintarantino]
5                                                             [stephenhopkins]
7                                                                [georgelucas]
                                         ...
57397                                                                       []
57398                                                                       []
57399                                                                       []
57400                                                                       []
57401                                                                       []
Name: crew, Length: 46684, dtype: object

In [222]:
df1[['cast','crew','keywords','overview','belongs_to_collection','genres','tagline']].sample(1)

,cast,crew,keywords,overview,belongs_to_collection,genres,tagline
55430,"[petraepperlein, christaepperlein, uweepperlein]","[petraepperlein, michaeltucker]","[stasi, surveillance, eastgermany]","[petra, epperlein, and, michael, tucker, (gunner, palace,, the, prisoner, or:, how, i, planned, to, kill, tony, blair), take, a, powerfully, personal, journey, through, the, former, east, germany,, as, epperlein, investigates, her, father’s, 1999, suicide, and, the, possibility, that, he, may, have, worked, as, a, spy, for, the, dreaded, stasi, security, service.]",[],[documentary],[]

In [223]:
cols = ['cast', 'crew', 'keywords', 'overview',
        'belongs_to_collection', 'genres', 'tagline']

for col in cols:
    print(col, type(df1[col].iloc[0]))

cast <class 'list'>
crew <class 'list'>
keywords <class 'list'>
overview <class 'list'>
belongs_to_collection <class 'list'>
genres <class 'list'>
tagline <class 'list'>

In [224]:
df1.columns

Index(['cast', 'crew', 'id', 'keywords', 'movieId', 'imdbId', 'tmdbId',
       'adult', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [225]:
print(df1['id'].isnull().sum())
print(df1['tmdbId'].isnull().sum())

1173
667

In [226]:
def clean_tmdbId(df):
    # rows where tmdbId is missing
    # but id exists
    mask = (
        df['tmdbId'].isnull() &
        df['id'].notnull()
    )

    # fill tmdbId using id
    df.loc[mask, 'tmdbId'] = df.loc[mask, 'id']

    # convert tmdbId to nullable integer
    df['tmdbId'] = df['tmdbId'].astype('Int64')

    return df

In [227]:
df1=clean_tmdbId(df1)
df1.drop(columns=['id'], inplace=True)

In [228]:
df1['tags'] = (
    df1['genres'] * 8 +
    df1['keywords'] * 3 +
    df1['cast'] * 2 +
    df1['crew'] 
    # df1['overview'].apply(lambda x: x[:20])
)

In [229]:
new_df=df1[['movieId','imdbId','tmdbId','title','tags']]

In [230]:
for col in new_df.columns:
    print(col, type(new_df[col].iloc[0]))

movieId <class 'numpy.float64'>
imdbId <class 'numpy.int64'>
tmdbId <class 'numpy.int64'>
title <class 'str'>
tags <class 'list'>

In [231]:
new_df['tags'] = new_df['tags'].apply(
    lambda x: ' '.join(x))

C:\Users\USER\AppData\Local\Temp\ipykernel_28520\2808956229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(

In [232]:
new_df.duplicated().sum()

np.int64(46)

In [233]:
new_df = new_df.drop_duplicates()

In [234]:
new_df.duplicated().sum()

np.int64(0)

In [235]:
new_df['tmdbId'].duplicated().sum()

np.int64(1036)

In [236]:
new_df[new_df['tmdbId'].duplicated(keep=False)].head(5)

,movieId,imdbId,tmdbId,title,tags
3660,6003.0,290538,4912,Confessions of a Dangerous Mind,comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller microfilm biography silencer intrigue microfilm biography silencer intrigue microfilm biography silencer intrigue samrockwell drewbarrymore juliaroberts samrockwell drewbarrymore juliaroberts georgeclooney
3662,144606.0,270288,4912,Confessions of a Dangerous Mind,comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller comedy crime drama romance thriller microfilm biography silencer intrigue microfilm biography silencer intrigue microfilm biography silencer intrigue samrockwell drewbarrymore juliaroberts samrockwell drewbarrymore juliaroberts georgeclooney
3921,7587.0,62229,5511,Le Samouraï,crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist alaindelon françoispérier nathaliedelon alaindelon françoispérier nathaliedelon jean-pierremelville
3923,27136.0,165303,5511,Le Samouraï,crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller crime drama thriller paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist paris bar jazz hearing garage hitman jazzclub police canary treason danger stakeout frenchnoir filmnoir lastjob professionalassassin verylittledialogue silentprotagonist alaindelon françoispérier nathaliedelon alaindelon françoispérier nathaliedelon jean-pierremelville
7770,4241.0,266860,10991,Pokémon: Spell of the Unknown,adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family adventure fantasy animation action family mountain mountainvillage friendship basedontvseries youngboy pokémon bestfriend fighting basedonvideogame pikachu anime mountain mountainvillage friendship basedontvseries youngboy pokémon bestfriend fighting basedonvideogame pikachu anime mountain mountainvillage friendship basedontvseries youngboy pokémon bestfriend fighting basedonvideogame pikachu anime veronicataylor rachaellillis ericstuart veronicataylor rachaellillis ericstuart michaelhaigney kunihikoyuyama

In [237]:
new_df = new_df.drop_duplicates(subset='tmdbId')

In [238]:
new_df['tmdbId'].duplicated().sum()

np.int64(0)

In [239]:
new_df['imdbId'].duplicated().sum()

np.int64(2)

In [240]:
new_df[new_df['imdbId'].duplicated(keep=False)].head()

,movieId,imdbId,tmdbId,title,tags
52567,170705.0,185906,331214,Band of Brothers,action drama war action drama war action drama war action drama war action drama war action drama war action drama war action drama war worldwarii u.s.army war paratroops miniseries combat warineurope paratrooper worldwarii u.s.army war paratroops miniseries combat warineurope paratrooper worldwarii u.s.army war paratroops miniseries combat warineurope paratrooper damianlewis ronlivingston frankjohnhughes damianlewis ronlivingston frankjohnhughes tomhanks davidfrankel philaldenrobinson mikaelsalomon richardloncraine davidnutter davidleland tonyto
55394,171495.0,81846,409926,Cosmos,
56433,7502.0,185906,191903,NaN,carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions
56451,77658.0,81846,205300,NaN,carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions carouselproductions visionviewentertainment telescenefilmgroupproductions

In [241]:
new_df = new_df.dropna(subset=['title'])

In [242]:
new_df['tags'].isnull().sum()*100/len(new_df)

np.float64(0.0)

In [243]:
new_df['tags']

0                                                                                                                                                                                                                                                                                                                                                                                                      drama crime drama crime drama crime drama crime drama crime drama crime drama crime drama crime underdog prison factoryworker prisoner helsinki independentfilm fallinginlove underdog prison factoryworker prisoner helsinki independentfilm fallinginlove underdog prison factoryworker prisoner helsinki independentfilm fallinginlove turopajala susannahaavisto mattipellonpää turopajala susannahaavisto mattipellonpää akikaurismäki
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  drama comedy drama comedy drama comedy drama comedy drama comedy drama comedy drama comedy drama comedy salesclerk helsinki garbage independentfilm salesclerk helsinki garbage independentfilm salesclerk helsinki garbage independentfilm mattipellonpää katioutinen sakarikuosmanen mattipellonpää katioutinen sakarikuosmanen akikaurismäki
3                                                                                                                                                                                                                                                                                                               crime comedy crime comedy crime comedy crime comedy crime comedy crime comedy crime comedy crime comedy hotel newyear'seve witch bet hotelroom sperm losangeles hoodlum womandirector episodefilm hotel newyear'seve witch bet hotelroom sperm losangeles hoodlum womandirector episodefilm hotel newyear'seve witch bet hotelroom sperm losangeles hoodlum womandirector episodefilm timroth antoniobanderas jenniferbeals timroth antoniobanderas jenniferbeals allisonanders alexandrerockwell robertrodriguez quentintarantino
5                                                                                                                                                                                                                                                                                                                                                                                                                      action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime chicago drugdealer boxingmatch escape onenight chicago drugdealer boxingmatch escape onenight chicago drugdealer boxingmatch escape onenight emilioestevez cubagoodingjr. denisleary emilioestevez cubagoodingjr. denisleary stephenhopkins
7        adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction adventure action sciencefiction android galaxy hermit deathstar lightsaber jedi rescuemission empire rebellion planet smuggler theforce spaceopera galacticwar stormtrooper totalitarianism android galaxy hermit deathstar lightsaber jedi rescuemission empire rebellion planet smuggler theforce spaceopera galacticwar stormtrooper totalitarianism android galaxy hermit deathstar lightsaber jedi rescuemission empire rebellion planet smuggler theforce spaceopera galacticwar stormtrooper totalitarianism markhamill harrisonford carriefisher markhamill harrisonford carriefisher georgelucas
                                                                                                                                                                                                                                                                                                                                                                                                                           ...
56125                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama karolinaantosik amelieleroy tessamcginn karolinaantosik amelieleroy tessamcginn mollysmith mauricesmith
56126                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        drama drama drama drama drama drama drama drama lloydbridges jackwarden rafaelcampos lloydbridges jackwarden rafaelcampos sidneylumet
56127                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  drama romance drama romance drama romance drama romance drama romance drama romance drama romance drama romance jackwitikka
56128                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        romance comedy romance comedy romance comedy romance comedy romance comedy romance comedy romance comedy romance comedy fantasy youth weird fantasy youth weird fantasy youth weird inkahaapamäki rosahonkonen tiitusrantala inkahaapamäki rosahonkonen tiitusrantala hannaleenahauru
56129                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama fantasy drama rubendefreitas teresamadruga fernandoheitor rubendefreitas teresamadruga fernandoheitor raúlruiz
Name: tags, Length: 45430, dtype: object

In [244]:

def remove_punctuation1(text):

    if isinstance(text, str):

        return text.translate(
            str.maketrans('', '', string.punctuation)
        )

    return text

In [245]:
new_df['tags'] = new_df['tags'].apply(remove_punctuation1)

In [246]:
import nltk

In [247]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [248]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [249]:
new_df['tags'] = new_df['tags'].apply(stem)

In [250]:
new_df['tags']

0                                                                                                                                                                                                                                                                                                                                          drama crime drama crime drama crime drama crime drama crime drama crime drama crime drama crime underdog prison factorywork prison helsinki independentfilm fallinginlov underdog prison factorywork prison helsinki independentfilm fallinginlov underdog prison factorywork prison helsinki independentfilm fallinginlov turopajala susannahaavisto mattipellonpää turopajala susannahaavisto mattipellonpää akikaurismäki
2                                                                                                                                                                                                                                                                                                                                                                                                                          drama comedi drama comedi drama comedi drama comedi drama comedi drama comedi drama comedi drama comedi salesclerk helsinki garbag independentfilm salesclerk helsinki garbag independentfilm salesclerk helsinki garbag independentfilm mattipellonpää katioutinen sakarikuosmanen mattipellonpää katioutinen sakarikuosmanen akikaurismäki
3                                                                                                                                                                                                                                                              crime comedi crime comedi crime comedi crime comedi crime comedi crime comedi crime comedi crime comedi hotel newyearsev witch bet hotelroom sperm losangel hoodlum womandirector episodefilm hotel newyearsev witch bet hotelroom sperm losangel hoodlum womandirector episodefilm hotel newyearsev witch bet hotelroom sperm losangel hoodlum womandirector episodefilm timroth antoniobandera jenniferb timroth antoniobandera jenniferb allisonand alexandrerockwel robertrodriguez quentintarantino
5                                                                                                                                                                                                                                                                                                                                                       action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime action thriller crime chicago drugdeal boxingmatch escap onenight chicago drugdeal boxingmatch escap onenight chicago drugdeal boxingmatch escap onenight emilioestevez cubagoodingjr denisleari emilioestevez cubagoodingjr denisleari stephenhopkin
7        adventur action sciencefict adventur action sciencefict adventur action sciencefict adventur action sciencefict adventur action sciencefict adventur action sciencefict adventur action sciencefict adventur action sciencefict android galaxi hermit deathstar lightsab jedi rescuemiss empir rebellion planet smuggler theforc spaceopera galacticwar stormtroop totalitarian android galaxi hermit deathstar lightsab jedi rescuemiss empir rebellion planet smuggler theforc spaceopera galacticwar stormtroop totalitarian android galaxi hermit deathstar lightsab jedi rescuemiss empir rebellion planet smuggler theforc spaceopera galacticwar stormtroop totalitarian markhamil harrisonford carriefish markhamil harrisonford carriefish georgeluca
                                                                                                                                                                                                                                                                                                                                                                                      ...
56125                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama karolinaantosik amelieleroy tessamcginn karolinaantosik amelieleroy tessamcginn mollysmith mauricesmith
56126                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   drama drama drama drama drama drama drama drama lloydbridg jackwarden rafaelcampo lloydbridg jackwarden rafaelcampo sidneylumet
56127                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               drama romanc drama romanc drama romanc drama romanc drama romanc drama romanc drama romanc drama romanc jackwitikka
56128                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     romanc comedi romanc comedi romanc comedi romanc comedi romanc comedi romanc comedi romanc comedi romanc comedi fantasi youth weird fantasi youth weird fantasi youth weird inkahaapamäki rosahonkonen tiitusrantala inkahaapamäki rosahonkonen tiitusrantala hannaleenahauru
56129                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama fantasi drama rubendefreita teresamadruga fernandoheitor rubendefreita teresamadruga fernandoheitor raúlruiz
Name: tags, Length: 45430, dtype: object

In [251]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create TF-IDF object
tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1,2)
)
vectors = tfidf.fit_transform(new_df['tags'])

# shape of matrix
print(vectors.shape)

(45430, 10000)

In [252]:
tfidf.get_feature_names_out()

array(['15thcenturi', '16thcenturi', '17thcenturi', ..., 'şenerşen',
       'моррисчестнат', 'эрикаэлениак'], dtype=object)

In [253]:
# from sklearn.decomposition import TruncatedSVD

# svd = TruncatedSVD(n_components=200, random_state=42)
# vectors_svd = svd.fit_transform(vectors)

In [254]:
from sklearn.metrics.pairwise import cosine_similarity

In [255]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(vectors)

NearestNeighbors(algorithm='brute', metric='cosine')

In [256]:
movie_index = pd.Series(new_df.index, index=new_df['title'])
def recommend(movie):
    idx = movie_index[movie]   # convert title → index

    distances, indices = model.kneighbors(vectors[idx], n_neighbors=10)

    for i in indices[0][1:]:
        print(new_df.iloc[i]['title'])

In [257]:
# movie_index = pd.Series(df1.index, index=df1['title'])
# def recommend(movie_title, n=10):

#     index = movie_index[movie_title]

#     distances, indices = model.kneighbors(
#         [vectors_svd[index]],
#         n_neighbors=n+1
#     )

#     for i in indices[0][1:]:
#         print(df1.iloc[i]['title'])

In [258]:
recommend('Batman Begins')

Still the Water
Restless Blood
Blue Week
You Are My Only Love
The Road
EM
Darling
Coming Home
The Country Teacher

In [259]:
new_df.iloc[21850].title

'The Silent House'

In [260]:
new_df[new_df['title']=='Avatar'].index[0]

np.int64(14391)

In [261]:
print(df1[['production_companies','adult']])
print(df1.adult.value_counts())

                                                                                                                              production_companies  \
0                                           [{'name': 'Villealfa Filmproduction Oy', 'id': 2303}, {'name': 'Finnish Film Foundation', 'id': 2396}]
2                                                                                            [{'name': 'Villealfa Filmproduction Oy', 'id': 2303}]
3                                                                        [{'name': 'Miramax Films', 'id': 14}, {'name': 'A Band Apart', 'id': 59}]
5      [{'name': 'Universal Pictures', 'id': 33}, {'name': 'Largo Entertainment', 'id': 1644}, {'name': 'JVC Entertainment Networks', 'id': 4248}]
7                                                  [{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]
...                                                                                                                                            ...
57397                                                                                                                                        False
57398                                                                                                                                        False
57399                                                                                                                                        False
57400                                                                                                                                        False
57401                                                                                                                                        False

                                                                                                                                adult
0                                                                                                                               False
2                                                                                                                               False
3                                                                                                                               False
5                                                                                                                               False
7                                                                                                                               False
...                                                                                                                               ...
57397                   Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.
57398   Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.
57399                                                                                                              - Written by Ørnås
57400                   Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.
57401   Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.

[46684 rows x 2 columns]
adult
False                                                                                                                             45502
 - Written by Ørnås                                                                                                                 391
 Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.                      391
 Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.      391
True                                                                                                                                  9
Name: count, dtype: int64

In [262]:
df1.adult.value_counts()

adult
False                                                                                                                             45502
 - Written by Ørnås                                                                                                                 391
 Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.                      391
 Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.      391
True                                                                                                                                  9
Name: count, dtype: int64

In [263]:
#making popularity column NaN where it contains non-numeric values
df1['popularity'] = pd.to_numeric(df1['popularity'], errors='coerce')

In [264]:
df1.popularity.value_counts()

popularity
0.000000     66
0.000001     56
0.000308     43
0.000220     40
0.000844     38
             ..
3.214001      1
1.075249      1
0.281008      1
0.347806      1
20.726578     1
Name: count, Length: 43757, dtype: int64

In [265]:
df1.columns

Index(['cast', 'crew', 'keywords', 'movieId', 'imdbId', 'tmdbId', 'adult',
       'belongs_to_collection', 'budget', 'genres', 'homepage',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count', 'tags'],
      dtype='object')