In [1]:
import sys
!{sys.executable} -m pip install vaderSentiment

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vaderSentiment in c:\users\khusi patra\appdata\roaming\python\python313\site-packages (3.3.2)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->vaderSentiment) (2025.11.12)

In [1]:
import numpy as np
import pandas as pd
import Dataset_Download
import cleaning
import recommender_system
from train_models import build_all_models
import warnings
warnings.filterwarnings('ignore')

In [2]:
Dataset_Download.download()

All Kaggle datasets processed!

In [3]:
df,combined_ratings=Dataset_Download.make_dataframe()

# Data Cleaning

In [4]:
cleaner=cleaning.DataCleaner()

In [5]:
# import nltk
# nltk.download('stopwords')
# nltk.download('punkt')

In [6]:
df,combined_ratings=cleaner.clean(df,combined_ratings)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42278 entries, 0 to 42277
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   keywords         28992 non-null  object
 1   movieId          42277 non-null  float64
 2   imdbId           42278 non-null  int64
 3   tmdbId           42278 non-null  int64
 4   genres           40002 non-null  object
 5   overview         41219 non-null  object
 6   tagline          18960 non-null  object
 7   title            42277 non-null  object
 8   tf_idf_title     42277 non-null  object
 9   Actors           39981 non-null  object
 10  Director         41417 non-null  object
 11  sentiment_score  40871 non-null  float64
 12  tags             42252 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 4.2+ MB

In [8]:
combined_ratings

          userId  movieId  rating   timestamp
0          38150     1176     4.0   789652004
1          44717       21     3.0   789652009
2            383       21     3.0   789652009
3            383       47     5.0   789652009
4            383     1079     3.0   789652009
...          ...      ...     ...         ...
26117927   85434     3210     2.0  1501828739
26117928   85434    82169     3.0  1501828746
26117929   85434     1013     4.0  1501828883
26117930  199634    60040     3.0  1501829623
26117931  179412   167786     3.5  1501829870

[26117932 rows x 4 columns]

# Recommendation

In [9]:
build_all_models(df, combined_ratings)

Both TF-IDF and SVD models already exist

In [10]:
recommend=recommender_system.recommender_system(df,combined_ratings)

In [11]:
#if any movie is not in the list
recommend.hybrid_recommendation(3,'Harry potter')

Empty DataFrame
Columns: [title, hybrid_score]
Index: []

In [12]:
#after using pickel it takes only 0.7 seconds to give the recommendation
recommend.hybrid_recommendation(1,'Captain America: The Winter Soldier')

,title,hybrid_score,svd_score,content_score,sentiment_score
0,The Godfather,0.510562,1.000000,0.003878,0.061368
1,Iron Man 2,0.416404,0.119034,0.782110,0.554326
2,Inception,0.412578,0.378974,0.284716,0.822938
3,Iron Man,0.411815,0.257201,0.621199,0.438632
4,Avengers: Age of Ultron,0.407887,0.071303,0.847950,0.503018
5,Ant-Man,0.382960,0.038398,0.755184,0.662978
6,Captain America: Civil War,0.379199,0.041194,1.000000,0.057344
7,The Godfather: Part II,0.378250,0.700887,0.006150,0.171026
8,Captain America: The First Avenger,0.365859,0.092091,0.875378,0.089537
9,X-Men: Days of Future Past,0.360711,0.099820,0.483145,0.944668

In [13]:
recommend.hybrid_recommendation(user_id=None, movie_title='Star Wars')

,title,hybrid_score,content_score,sentiment_score
0,The Empire Strikes Back,0.781470,1.000000,0.125881
1,Star Wars: The Force Awakens,0.706522,0.651328,0.872105
2,The Star Wars Holiday Special,0.623458,0.589585,0.725076
3,Star Wars: Episode III - Revenge of the Sith,0.566326,0.740667,0.043303
4,Return of the Jedi,0.561410,0.667311,0.243706
5,Rogue One: A Star Wars Story,0.546783,0.467547,0.784491
6,Star Wars: Episode II - Attack of the Clones,0.442132,0.463628,0.377644
7,Threads of Destiny,0.431828,0.412293,0.490433
8,Star Wars: The Clone Wars,0.425365,0.298607,0.805639
9,Toward the Terra,0.409206,0.234093,0.934542

In [14]:
recommend.hybrid_recommendation(user_id=None, movie_title='Avatar 2')

,title,hybrid_score,content_score,sentiment_score
0,Avatar,0.998491,1.000000,0.993964
1,Justin Time,0.809770,0.752397,0.981891
2,Toward the Terra,0.734215,0.667752,0.933602
3,The Island at the Top of the World,0.732771,0.685948,0.873239
4,The Last Airbender,0.695250,0.608422,0.955734
5,Fly Me to the Moon,0.682691,0.611126,0.897384
6,Devil of the Desert Against the Son of Hercules,0.669265,0.566733,0.976861
7,Once Upon a Warrior,0.657414,0.615318,0.783702
8,L: Change the World,0.656652,0.637106,0.715292
9,On the Silver Globe,0.649641,0.556329,0.929577

In [15]:
recommend.hybrid_recommendation(user_id=1)

,title,hybrid_score,svd_score,sentiment_score
0,The Godfather,0.765342,1.000000,0.061368
1,The Godfather: Part II,0.568422,0.700887,0.171026
2,Inception,0.489965,0.378974,0.822938
3,Fight Club,0.479089,0.598209,0.121730
4,Harry Potter and the Deathly Hallows: Part 2,0.401192,0.220368,0.943662
5,The Dark Knight,0.400185,0.525867,0.023139
6,Dead Poets Society,0.379193,0.217530,0.864185
7,Eternal Sunshine of the Spotless Mind,0.340114,0.192252,0.783702
8,Harry Potter and the Philosopher's Stone,0.336342,0.155028,0.880282
9,Avatar,0.333907,0.113889,0.993964